import useSWR from 'swr';
import useSWRMutation from 'swr/mutation';
import axios from 'axios';
import { fetchTipHeight, fetchChainFeeRate } from '@/lib/utils';
const fetcher = (args) =>
  fetch(args)
    .then((res) => res.json())
    .then(({ code, msg, data }) => {
      if (code === 0) {
        return data;
      } else {
        console.log('error: ' + msg);
      }
    });

const { VITE_API_HOST } = import.meta.env;
interface Ord2ListStatusParams {
  start: number;
  limit: number;
  sort?: string;
  ticker_hex?: string;
  complete?: string;
}
export const generateUrl = (url: string) => {
  return `${VITE_API_HOST}/ordx/${url}`;
};
export const useOrd2Status = ({ start, limit }: Ord2ListStatusParams) => {
  console.log(start);
  console.log(limit);
  const { data, error, isLoading } = useSWR(
    generateUrl('v1/indexer/ordx/status'),
    fetcher,
  );
  return {
    data,
    error,
    isLoading,
  };
};

interface Ord2InfoParams {
  tick?: string;
}
export const useOrd2Info = ({ tick }: Ord2InfoParams) => {
  const { data, error, isMutating, trigger, reset } = useSWRMutation(
    generateUrl(`v1/indexer/ordx/${tick}/info`),
    fetcher,
  );
  return {
    data,
    trigger,
    reset,
    error,
    isLoading: isMutating,
  };
};
export const requstOrd2Info = async ({ tick }: Ord2InfoParams) => {
  const { data } = await axios.get(generateUrl(`v1/indexer/ordx/${tick}/info`));
  return data;
};
interface Ord2SummaryParams {
  address?: string;
}
export const useBtcHeight = (network: 'testnet' | 'main') => {
  const { data, error, isLoading } = useSWR(network, (n) => fetchTipHeight(n));
  return {
    data,
    error,
    isLoading,
  };
};
export const useBtcFeeRate = (network: 'testnet' | 'main') => {
  const { data, error, isLoading } = useSWR(network, (n) =>
    fetchChainFeeRate(n),
  );
  return {
    data,
    error,
    isLoading,
  };
};
export const useOrd2Summary = ({ address }: Ord2SummaryParams) => {
  const { data, error, isLoading } = useSWR(
    generateUrl(`v1/indexer/ordx/${address}/info`),
    fetcher,
  );
  return {
    data: {
      height: 824129,
      total: 92,
      start: 0,
      detail: [
        {
          ticker: 'ARKJ',
          overallBalance: '4999999999999999999',
          transferableBalance: '0',
          availableBalance: '4999999999999999999',
          availableBalanceSafe: '4999999999999999999',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'ARKV',
          overallBalance: '3000000000000000000',
          transferableBalance: '0',
          availableBalance: '3000000000000000000',
          availableBalanceSafe: '3000000000000000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'XOKX',
          overallBalance: '1926667796914166711',
          transferableBalance: '0',
          availableBalance: '1926667796914166711',
          availableBalanceSafe: '1926667796914166711',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'X.OK',
          overallBalance: '333333333333333333',
          transferableBalance: '0',
          availableBalance: '333333333333333333',
          availableBalanceSafe: '333333333333333333',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'FC2 ',
          overallBalance: '90000000000000000',
          transferableBalance: '0',
          availableBalance: '90000000000000000',
          availableBalanceSafe: '90000000000000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'satk',
          overallBalance: '2000000000000000',
          transferableBalance: '0',
          availableBalance: '2000000000000000',
          availableBalanceSafe: '2000000000000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'sats',
          overallBalance: '30305060860480',
          transferableBalance: '20229711705322',
          availableBalance: '10075349155158',
          availableBalanceSafe: '10075349155158',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'OKBL',
          overallBalance: '440000000000',
          transferableBalance: '0',
          availableBalance: '440000000000',
          availableBalanceSafe: '440000000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'rats',
          overallBalance: '61222493087',
          transferableBalance: '1730536541',
          availableBalance: '59491956546',
          availableBalanceSafe: '59491956546',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: '𝛑',
          overallBalance: '21800000000',
          transferableBalance: '0',
          availableBalance: '21800000000',
          availableBalanceSafe: '21800000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: '$DOG',
          overallBalance: '10888888888',
          transferableBalance: '0',
          availableBalance: '10888888888',
          availableBalanceSafe: '10888888888',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: '$HMC',
          overallBalance: '1000000000',
          transferableBalance: '0',
          availableBalance: '1000000000',
          availableBalanceSafe: '1000000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: '📖',
          overallBalance: '250000000',
          transferableBalance: '0',
          availableBalance: '250000000',
          availableBalanceSafe: '250000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'SHBL',
          overallBalance: '133333332',
          transferableBalance: '0',
          availableBalance: '133333332',
          availableBalanceSafe: '133333332',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'GDPs',
          overallBalance: '100000000',
          transferableBalance: '0',
          availableBalance: '100000000',
          availableBalanceSafe: '100000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'Gas.',
          overallBalance: '100000000',
          transferableBalance: '0',
          availableBalance: '100000000',
          availableBalanceSafe: '100000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'NOOT',
          overallBalance: '99930154',
          transferableBalance: '53894075',
          availableBalance: '46036079',
          availableBalanceSafe: '46036079',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'chax',
          overallBalance: '97053414.46423425824',
          transferableBalance: '0',
          availableBalance: '97053414.46423425824',
          availableBalanceSafe: '97053414.46423425824',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'csas',
          overallBalance: '88526024',
          transferableBalance: '6962499',
          availableBalance: '81563525',
          availableBalanceSafe: '81563525',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'mice',
          overallBalance: '50102205.984488',
          transferableBalance: '660777.86256',
          availableBalance: '49441428.121928',
          availableBalanceSafe: '49441428.121928',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'вns',
          overallBalance: '42000000',
          transferableBalance: '0',
          availableBalance: '42000000',
          availableBalanceSafe: '42000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'PPIE',
          overallBalance: '20999500',
          transferableBalance: '0',
          availableBalance: '20999500',
          availableBalanceSafe: '20999500',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'HUID',
          overallBalance: '20895000',
          transferableBalance: '0',
          availableBalance: '20895000',
          availableBalanceSafe: '20895000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'VMPX',
          overallBalance: '14590435',
          transferableBalance: '718143',
          availableBalance: '13872292',
          availableBalanceSafe: '13872292',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'TURT',
          overallBalance: '11702516.5604786',
          transferableBalance: '145203.216907',
          availableBalance: '11557313.3435716',
          availableBalanceSafe: '11557313.3435716',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'drac',
          overallBalance: '10578557',
          transferableBalance: '370448',
          availableBalance: '10208109',
          availableBalanceSafe: '10208109',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'OXCT',
          overallBalance: '10000000',
          transferableBalance: '0',
          availableBalance: '10000000',
          availableBalanceSafe: '10000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'bank',
          overallBalance: '8610962',
          transferableBalance: '329517',
          availableBalance: '8281445',
          availableBalanceSafe: '8281445',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'MUBI',
          overallBalance: '7309733',
          transferableBalance: '0',
          availableBalance: '7309733',
          availableBalanceSafe: '7309733',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'bDRC',
          overallBalance: '7000000',
          transferableBalance: '0',
          availableBalance: '7000000',
          availableBalanceSafe: '7000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'ArkS',
          overallBalance: '5113476',
          transferableBalance: '1595746',
          availableBalance: '3517730',
          availableBalanceSafe: '3517730',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'psps',
          overallBalance: '5000000',
          transferableBalance: '0',
          availableBalance: '5000000',
          availableBalanceSafe: '5000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'SHIB',
          overallBalance: '5000000',
          transferableBalance: '0',
          availableBalance: '5000000',
          availableBalanceSafe: '5000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'ORPG',
          overallBalance: '5000000',
          transferableBalance: '0',
          availableBalance: '5000000',
          availableBalanceSafe: '5000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'BTOG',
          overallBalance: '5000000',
          transferableBalance: '0',
          availableBalance: '5000000',
          availableBalanceSafe: '5000000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'Majo',
          overallBalance: '4694531',
          transferableBalance: '33716',
          availableBalance: '4660815',
          availableBalanceSafe: '4660815',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'insc',
          overallBalance: '3241468.154379',
          transferableBalance: '98709.8',
          availableBalance: '3142758.354379',
          availableBalanceSafe: '3142758.354379',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'RDEX',
          overallBalance: '3097527.6508426',
          transferableBalance: '22869.93',
          availableBalance: '3074657.7208426',
          availableBalanceSafe: '3074657.7208426',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'pepe',
          overallBalance: '2894531',
          transferableBalance: '164648',
          availableBalance: '2729883',
          availableBalanceSafe: '2729883',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: '$BSV',
          overallBalance: '2473308',
          transferableBalance: '103209',
          availableBalance: '2370099',
          availableBalanceSafe: '2370099',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'BNSx',
          overallBalance: '2038242.601009',
          transferableBalance: '24736.220653',
          availableBalance: '2013506.380356',
          availableBalanceSafe: '2013506.380356',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'trac',
          overallBalance: '1869479',
          transferableBalance: '110389',
          availableBalance: '1759090',
          availableBalanceSafe: '1759090',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'biso',
          overallBalance: '1741399',
          transferableBalance: '0',
          availableBalance: '1741399',
          availableBalanceSafe: '1741399',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'MMSS',
          overallBalance: '1652730.91678477',
          transferableBalance: '0',
          availableBalance: '1652730.91678477',
          availableBalanceSafe: '1652730.91678477',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'piza',
          overallBalance: '1210686',
          transferableBalance: '94494',
          availableBalance: '1116192',
          availableBalanceSafe: '1116192',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: '1cat',
          overallBalance: '1016649.912575',
          transferableBalance: '0',
          availableBalance: '1016649.912575',
          availableBalanceSafe: '1016649.912575',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'nals',
          overallBalance: '998670',
          transferableBalance: '727202',
          availableBalance: '271468',
          availableBalanceSafe: '271468',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'biop',
          overallBalance: '578880',
          transferableBalance: '0',
          availableBalance: '578880',
          availableBalanceSafe: '578880',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: '  OM',
          overallBalance: '500000',
          transferableBalance: '0',
          availableBalance: '500000',
          availableBalanceSafe: '500000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'BTCs',
          overallBalance: '272481.193238',
          transferableBalance: '14559.60338353',
          availableBalance: '257921.58985447',
          availableBalanceSafe: '257921.58985447',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'xexe',
          overallBalance: '210000',
          transferableBalance: '0',
          availableBalance: '210000',
          availableBalanceSafe: '210000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'bc1q',
          overallBalance: '200000',
          transferableBalance: '0',
          availableBalance: '200000',
          availableBalanceSafe: '200000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'ordi',
          overallBalance: '192296',
          transferableBalance: '139465',
          availableBalance: '52831',
          availableBalanceSafe: '52831',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'Lufy',
          overallBalance: '150000',
          transferableBalance: '0',
          availableBalance: '150000',
          availableBalanceSafe: '150000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'MCSP',
          overallBalance: '100000',
          transferableBalance: '0',
          availableBalance: '100000',
          availableBalanceSafe: '100000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'AOTS',
          overallBalance: '100000',
          transferableBalance: '0',
          availableBalance: '100000',
          availableBalanceSafe: '100000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'ceox',
          overallBalance: '100000',
          transferableBalance: '0',
          availableBalance: '100000',
          availableBalanceSafe: '100000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'BETF',
          overallBalance: '20000',
          transferableBalance: '0',
          availableBalance: '20000',
          availableBalanceSafe: '20000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'ETCS',
          overallBalance: '10668',
          transferableBalance: '0',
          availableBalance: '10668',
          availableBalanceSafe: '10668',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'nowo',
          overallBalance: '10000',
          transferableBalance: '0',
          availableBalance: '10000',
          availableBalanceSafe: '10000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'meme',
          overallBalance: '2400',
          transferableBalance: '36',
          availableBalance: '2364',
          availableBalanceSafe: '2364',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'PGID',
          overallBalance: '2000',
          transferableBalance: '0',
          availableBalance: '2000',
          availableBalanceSafe: '2000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'DGOO',
          overallBalance: '2000',
          transferableBalance: '0',
          availableBalance: '2000',
          availableBalanceSafe: '2000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'moon',
          overallBalance: '1001',
          transferableBalance: '0',
          availableBalance: '1001',
          availableBalanceSafe: '1001',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: '𓃠',
          overallBalance: '1000',
          transferableBalance: '0',
          availableBalance: '1000',
          availableBalanceSafe: '1000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: '𓃰',
          overallBalance: '1000',
          transferableBalance: '0',
          availableBalance: '1000',
          availableBalanceSafe: '1000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'DETF',
          overallBalance: '1000',
          transferableBalance: '0',
          availableBalance: '1000',
          availableBalanceSafe: '1000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'ARKK',
          overallBalance: '1000',
          transferableBalance: '0',
          availableBalance: '1000',
          availableBalanceSafe: '1000',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'PYUS',
          overallBalance: '999',
          transferableBalance: '0',
          availableBalance: '999',
          availableBalanceSafe: '999',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'XOVA',
          overallBalance: '888',
          transferableBalance: '0',
          availableBalance: '888',
          availableBalanceSafe: '888',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'ARKB',
          overallBalance: '810',
          transferableBalance: '0',
          availableBalance: '810',
          availableBalanceSafe: '810',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'crb2',
          overallBalance: '600',
          transferableBalance: '0',
          availableBalance: '600',
          availableBalanceSafe: '600',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'UTXO',
          overallBalance: '482',
          transferableBalance: '0',
          availableBalance: '482',
          availableBalanceSafe: '482',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'TEXO',
          overallBalance: '400',
          transferableBalance: '0',
          availableBalance: '400',
          availableBalanceSafe: '400',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'BTC\u000b',
          overallBalance: '116',
          transferableBalance: '0',
          availableBalance: '116',
          availableBalanceSafe: '116',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: ' ₿',
          overallBalance: '100',
          transferableBalance: '0',
          availableBalance: '100',
          availableBalanceSafe: '100',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'aisi',
          overallBalance: '100',
          transferableBalance: '0',
          availableBalance: '100',
          availableBalanceSafe: '100',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'WBEI',
          overallBalance: '100',
          transferableBalance: '0',
          availableBalance: '100',
          availableBalanceSafe: '100',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: '𓃱',
          overallBalance: '50',
          transferableBalance: '0',
          availableBalance: '50',
          availableBalanceSafe: '50',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'rcsv',
          overallBalance: '20',
          transferableBalance: '0',
          availableBalance: '20',
          availableBalanceSafe: '20',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'libx',
          overallBalance: '10',
          transferableBalance: '0',
          availableBalance: '10',
          availableBalanceSafe: '10',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'JSON',
          overallBalance: '5',
          transferableBalance: '0',
          availableBalance: '5',
          availableBalanceSafe: '5',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: '🀄',
          overallBalance: '1',
          transferableBalance: '0',
          availableBalance: '1',
          availableBalanceSafe: '1',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'bili',
          overallBalance: '1',
          transferableBalance: '0',
          availableBalance: '1',
          availableBalanceSafe: '1',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: ' imx',
          overallBalance: '1',
          transferableBalance: '0',
          availableBalance: '1',
          availableBalanceSafe: '1',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'fanz',
          overallBalance: '1',
          transferableBalance: '0',
          availableBalance: '1',
          availableBalanceSafe: '1',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: '1000',
          overallBalance: '1',
          transferableBalance: '0',
          availableBalance: '1',
          availableBalanceSafe: '1',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'Xsec',
          overallBalance: '1',
          transferableBalance: '0',
          availableBalance: '1',
          availableBalanceSafe: '1',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: '1984',
          overallBalance: '0',
          transferableBalance: '0',
          availableBalance: '0',
          availableBalanceSafe: '0',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'OKBI',
          overallBalance: '0',
          transferableBalance: '0',
          availableBalance: '0',
          availableBalanceSafe: '0',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'cnpo',
          overallBalance: '0',
          transferableBalance: '0',
          availableBalance: '0',
          availableBalanceSafe: '0',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
        {
          ticker: 'X.IO',
          overallBalance: '0',
          transferableBalance: '0',
          availableBalance: '0',
          availableBalanceSafe: '0',
          availableBalanceUnSafe: '0',
          decimal: 18,
        },
      ],
    },
    error,
    isLoading,
  };
};
